id: b72d153e347c49588ae8ece13ec6f774
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN844
  title: སྤྱི་ལོ ༢༠༠༩་ལོར་དཔལ་སྤུངས་དགོན་གཞུང་ནས་ཉར་ཚགས་བྱས་པའི་གནའ་དཔེ་བྲིས་མའི་གློག་རྡུལ་འདྲ་བཤུས།
  volumes:
    7eb0627d98d74b7ba87b0d603df1eed3:
      image_group_id: I2KG229636
      title: ''
      base_file: v001.txt
  author: ''
